import os
os.system ('clear')
os.system ('clear')                                                                                  
os.system ('sl')
os.system('clear')
print ('\033[1;36mحﺎﭴﻧﺑ مﺗ')
os.system ('figlet HK instagram')
print ("")
print ("")
print (" \033[1;32m بﺎﺴﺤ مﺴإ  \033[1;33m: bayan__.777")
print ("")
print ("")
print (" \033[1;32mفﺗﺎﮩﻟ مﻗر/ ﺪﯾﺮﺑ \033[1;33m: snexys200i@gmail.com")
print ("")
print ("")
print (" \033[1;32mةﺮﻏﺗ :\033[1;33m ‏幸{H1>>|微你ph ؟؟: 1")
print ("")
print ("")
os.system ('figlet')

